version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: skillforge_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: skillforge_db
      MYSQL_USER: skillforge_user
      MYSQL_PASSWORD: SenhaForte123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: skillforge-app
    container_name: skillforge_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/skillforge_db
      SPRING_DATASOURCE_USERNAME: skillforge_user
      SPRING_DATASOURCE_PASSWORD: SenhaForte123
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
