spring:
  application:
    name: SkillForge

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://skillforgedb.c506c4ogq3yn.sa-east-1.rds.amazonaws.com:5432/skillforge
    username: postgres
    password: Skillforge

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG

  docker:
    compose:
      enabled: false
