spring:
  application:
    name: SkillForge

  docker:
    compose:
      enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect  # Dialeto para PostgreSQL 9.5 ou mais recente
    properties:
      hibernate.format_sql: true
logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
