spring:
  application:
    name: SkillForge

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:h2:mem:testdb  # Banco em memória
    driverClassName: org.h2.Driver
    username: duds
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop  # Cria e limpa o banco a cada reinício da aplicação
  h2:
    console:
      enabled: true  # Habilita o console H2 acessível via navegador
