spring:
  application:
    name: SkillForge

  docker:
    compose:
      enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
